### ISSUE TITLE
Bug fixer of no-dispatch-in-effects

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/eslint-plugin-ngrx#230]
## Behavior

The fixer introduced in #220 doesn't cover all cases and leads to incorrect behavior.

## Code snippet

In the following code snippet, the fixer removes the `dispatch` which is fine.

```ts
 map((books: Book[]) =>
              this.store.dispatch(BooksApiActions.searchSuccess({ books }))
),
```

But if we replace the `map` operator with the `tap` operator the fix is the same:

```ts
 tap((books: Book[]) =>
              (BooksApiActions.searchSuccess({ books }))
),
```

This changes the behavior because now, `BooksApiActions.searchSuccess` isn't dispatched.
I think this can become dangerous if used with the `--fix` flag.
Because of that reason, we should either make the fix smarter (is it possible to cover all cases?), or just to revert the change and implement it as a suggestion.

## I would be willing to submit a PR to fix this issue :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by rafaelss95** [comment]
Oh man, I didn't really think about this case. I don't think there's really a way to make the fix secure, as `store.dispatch` can appear anywhere, not just inside a `map`.

And another thing worth mentioning is that some tests don't even compile if copied into a real application (from what I've seen it's been like this since the creation of the rule, it's not something that's been added recently), for example:

```ts
map(() => this.store.dispatch({ type: 'PONG' })),
```

... is not valid, as `store.dispatch` is `void` and therefore invalid for `map`.

I really wish we could test with real code instead of magic strings 😅 (but, yes, I know that's how ESLint works)

---

That being said, do you want me to convert the fix to suggestion or are you going to do it?

**Comment by timdeschryver** [comment]
your call @rafaelss95 , I'm fine either way 😁
