### ISSUE TITLE
404 for no-multiple-actions-in-effects docs

### ISSUE THREAD

**Issue by patoncrispy** [timdeschryver/eslint-plugin-ngrx#38]
It seems the docs for the `no-multiple-actions-in-effects` rule is missing.

I feel like I'm learning so much about NGRX having these linting rules in place! :) What is wrong with dispatching multiple actions in an effect, out of curiosity? Googling 'multiple actions in effects' produces many results with articles showing how to do it, so it seems to be a reasonably popular request! It would be great to understand why this might be an anti-pattern, of sorts.

**Comment by timdeschryver** [comment]
Oops, good catch @patoncrispy ! Thanks for creating this issue.
If you feel like, you can create the file.
That way, it won't be forgotten when we actually add the reasoning behind the rules (with some examples) to the docs 😅

Now, to answer your question...
It's basically the same as the [avoid-dispatching-multiple-actions-sequentially](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/src/rules/avoid-dispatching-multiple-actions-sequentially.ts) rule. An action should describe a unique event that happened in the application.

For example, we think it's better to have an action `CustomerDataLoaded` instead of [`SetCustomerData`, `SetCustomerOrders`].
