### ISSUE TITLE
Rule Request: No duplicate Action names

### ISSUE THREAD

**Issue by craig-dae** [timdeschryver/eslint-plugin-ngrx#60]
Rule Request: Provide a rule that will catch the following mistake, where the same action name was used twice, causing a potential infinite loop in the `effects`:

```js
export const CreateSomething = createAction(
  '[Something] Create Something Success',
);

export const CreateSomethingSuccess = createAction(
  '[Something] Create Something Success',
);
```

**Comment by timdeschryver** [comment]
Hi, thanks for reaching out. 
This was a part of ngrx-tslint-rules, be we didn't port it over to the eslint version because it is now part of NgRx.
You can enable the [strictActionTypeUniqueness
 runtime check](https://ngrx.io/guide/store/configuration/runtime-checks#strictactiontypeuniqueness), which will throw an error when an action type is registered twice.

**Comment by craig-dae** [comment]
Just applied this to my configuration. This is perfect. Thanks!
