### ISSUE TITLE
An option or a rule to forbid the use of operators with `select`

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#76]
Not sure if it's outside of the scope of the rule `avoid-mapping-selectors`, but I'd like have a way to forbid the use of any operator with `store.select`/`store.pipe(select)`, so these would be invalid:

```
// create a selector and do anything you want there.
readonly loggedIn$ = this.store$.select(AuthSelectors.selectUser).pipe(filter(Boolean))
readonly loggedIn$ = this.store$.pipe(select(AuthSelectors.selectUser), filter(Boolean))
```

**Comment by timdeschryver** [comment]
The `avoid-mapping-selectors` rule is there because you can solve this by creating a new selector. This is a best practice because it's easier to read and to test.

The new proposed rule can be more strict, but I wouldn't add it to the recommended rules because it might make sense to filter values from a selector when the store isn't populated yet, or to use a debounce operator for performance reasons.

Feel free to create this rule if it helps you. I was we could make this a configurable rule that by default forbids all operators, unless that operator was marked as safe to use. Something similar to https://github.com/cartant/eslint-plugin-rxjs/blob/main/docs/rules/ban-operators.md
